Greeting.create(greeting: "Hello, Prantosh!")
Greeting.create(greeting: "Hello, Aman!")
Greeting.create(greeting: "Hello, Hein!")
Greeting.create(greeting: "Hello, Utsargo!")
Greeting.create(greeting: "Hello, Salwa!")